name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  build-push-frontend-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract version and set it to TAG env var
        run: |
          echo "TAG=$(jq -r '.version' package.json)" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          # context: "{{defaultContext}}"
          push: true
          tags: |
            moonlyss/geos-ui-frontend:latest
            moonlyss/geos-ui-frontend:${{ env.TAG }}
