name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  build-push-frontend-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Get version from package.json
        id: package_version
        run: echo "::set-output name=version::$(jq -r '.version' package.json)"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: moonlyss/geos-ui-frontend:${{ steps.package_version.outputs.version }}
      -
        name: Build and push Backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}"
          push: true
          tags: moonlyss/geos-ui-frontend:latest
